### ISSUE TITLE
stop deep imports of agoric CLI package

### ISSUE THREAD

**Issue by turadg** [Agoric/testnet-load-generator#112]
https://github.com/Agoric/agoric-sdk/pull/7824 attempted to remove exports from the `agoric` package so that it's only used for its `bin` install. 

That [broke loadgen CI](https://github.com/Agoric/agoric-sdk/actions/runs/5313843686/jobs/9620286206?pr=7824),
```
(Error#1)
Error#1: Package subpath './lib/helpers.js' is not defined by "exports" in /usr/src/testnet-load-generator/runner/node_modules/agoric/package.json

  at resolve (file:///usr/src/testnet-load-generator/runner/lib/helpers/module.js:26:32)
  at getSDKBinaries (file:///usr/src/testnet-load-generator/runner/lib/main.js:172:33)
  at async Promise.all (index 0)
  at async main (file:///usr/src/testnet-load-generator/runner/lib/main.js:329:49)
```

For now I've restored the two exports loadgen expects, https://github.com/Agoric/testnet-load-generator/blob/0e2b8910edc95e5890d4e7ff394968c8d02a4b9d/runner/lib/main.js#L165-L167

A more maintainable solution would be for the interface between loadgen and the `agoric` package to use the CLI.

**Comment by mhofman** [comment]
That one is gonna be tricky. If we rely on the CLI, we should add a CLI option to get the path of the binaries.

cc @michaelfig, any thoughts? I know you've been thinking about build artifacts, and this is somewhat relevant.
